### ISSUE TITLE
可以考虑使用JitPack发布库文件

### ISSUE THREAD

**Issue by stars-one** [GituioPyeb/custom-view-view-load-status#1]
如题,可以考虑使用JitPack发布库文件,可以更方便引用库来使用

如果不熟悉流程,可以参考下我的文章[Jitpack发布Android库带文档和源码 - Stars-One的杂货小窝](https://stars-one.site/2023/08/30/jitpack-library-with-doc)

**Comment by GituioPyeb** [comment]
好的，多谢大佬指点
